# Generated by Django 5.0.4 on 2024-04-12 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowing",
            name="actual_return_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
