# Generated by Django 5.0.4 on 2024-04-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowing", "0002_alter_borrowing_actual_return_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowing",
            name="borrow_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
